c++: note other candidates when diagnosing deletedness
With the previous two patches in place, we can now extend our
deletedness diagnostic to note the other considered candidates, e.g.:

  deleted.C: In function 'int main()':
  deleted.C:10:4: error: use of deleted function 'void f(int)'
     10 |   f(0);
        |   ~^~~
  deleted.C:5:6: note: declared here
      5 | void f(int) = delete;
        |      ^
  deleted.C:5:6: note: candidate: 'void f(int)' (deleted)
  deleted.C:6:6: note: candidate: 'void f(...)'
      6 | void f(...);
        |      ^
  deleted.C:7:6: note: candidate: 'void f(int, int)'
      7 | void f(int, int);
        |      ^
  deleted.C:7:6: note:   candidate expects 2 arguments, 1 provided

These notes are controlled by a new command line flag
-fdiagnostics-all-candidates which also controls whether we note
ignored candidates more generally.

gcc/ChangeLog:

	* doc/invoke.texi (C++ Dialect Options): Document
	-fdiagnostics-all-candidates.

gcc/c-family/ChangeLog:

	* c.opt: Add -fdiagnostics-all-candidates.

gcc/cp/ChangeLog:

	* call.cc (print_z_candidates): Only print ignored candidates
	when -fdiagnostics-all-candidates is set, otherwise suggest
	the flag.
	(build_over_call): When diagnosing deletedness, note
	other candidates only if -fdiagnostics-all-candidates is
	set, otherwise suggest the flag.

gcc/testsuite/ChangeLog:

	* g++.dg/overload/error6.C: Pass -fdiagnostics-all-candidates.
	* g++.dg/cpp0x/deleted16.C: New test.
	* g++.dg/cpp0x/deleted16a.C: New test.
	* g++.dg/overload/error6a.C: New test.